services:
  # 1. SERVIZIO LARAVEL/PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network

  # 2. SERVIZIO NGINX (WEB SERVER)
  nginx:
    image: nginx:stable-alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel_network

  # 3. SERVIZIO DATABASE (MYSQL)
  db:
    image: mysql:8.0
    container_name: laravel-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: minicrocera
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network

# Reti e Volumi
networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local